#!/usr/bin/env bash
# Regenerates the Android launcher icon (android/app/src/main/res/mipmap-*/)
# from assets/icon/app_icon.png using flutter_launcher_icons. That output
# directory is gitignored and regenerated by `flutter create` -- same
# problem class as the manifest/build.gradle patches. Run this after every
# `flutter create --platforms=android .`, alongside
# scripts/patch_android_manifest.sh and scripts/patch_android_build_gradle.sh.
set -euo pipefail

if [ ! -f "assets/icon/app_icon.png" ]; then
  echo "assets/icon/app_icon.png not found -- nothing to generate from" >&2
  exit 1
fi

dart run flutter_launcher_icons
